### ISSUE TITLE
Automatically try to obtain auth for portalConfig if not present

### ISSUE THREAD

**Issue by miketalley** [HubSpot/hubspot-cms-tools#91]
When updating the config manually to...
```
defaultPortal: 'DEV'
# List of portals that are intended to be used
portals:
  # Portal set up to use an API Key
  - name: 'DEV'
    portalId: <portalId>
    authType: 'personalaccesskey'
    personalAccessKey: 'xxxxxxx'
    env: 'QA'
```

an error is encountered:
```[ERROR] The portalId <portalId> is missing authentication configuration```

We should try to obtain the missing auth data in the config if we have the means to before throwing an error.
