### ISSUE TITLE
env: QA getting stripped from personalaccesskey refresh

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cms-tools#94]
If my config is in this state, where I just entered my personalAccessKey
```
portals:
  - name: DEV
    env: QA
    portalId: 100754221
    authType: personalaccesskey
    personalAccessKey: xxxxxxx
```
and then run a command, `env: QA` is getting stripped from the config, and it ends up like:
```
portals:
  - name: DEV
    portalId: 100754221
    authType: personalaccesskey
    personalAccessKey: >- xxxx
    auth:
      tokenInfo:
        accessToken: >- xxxxx
        expiresAt: 'xxxxx'
```
